"""add refresh_log table

Revision ID: 1d90b32a1335
Revises: 9fa75df0d0a5
Create Date: 2026-09-02 23:30:00.785964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d90b32a1335'
down_revision: Union[str, Sequence[str], None] = '9fa75df0d0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_log')
    # ### end Alembic commands ###
