"""add rejected job status

Revision ID: a43bc5460e9b
Revises: 1d90b32a1335
Create Date: 2026-09-03 14:52:17.125181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43bc5460e9b'
down_revision: Union[str, Sequence[str], None] = '1d90b32a1335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Adds 'rejected' to the existing `jobstatus` Postgres ENUM type
    (models.py's JobStatus) - NOT autogenerated, since Alembic's
    autogenerate doesn't reliably detect enum VALUE additions the way
    it does column/table changes.

    `ALTER TYPE ... ADD VALUE` must run outside a normal transaction
    block in Postgres (the new value can't be used in the same
    transaction it was added in) - `autocommit_block()` is Alembic's
    documented way to do that, rather than wrapping this migration in
    the usual transactional DDL the rest of this project's migrations
    get for free.
    """
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE jobstatus ADD VALUE 'rejected'")


def downgrade() -> None:
    """
    Deliberately NOT reversible: Postgres has no `ALTER TYPE ... DROP
    VALUE` - removing an enum value requires recreating the whole type
    (and every column/index that uses it) from scratch, which is
    real, destructive surgery, not a one-line command. Left as a
    documented gap rather than faking a downgrade that would either
    silently do nothing or risk data loss.
    """
    raise NotImplementedError(
        "Cannot drop an enum value in Postgres without recreating the jobstatus type - "
        "not implemented; roll back to a backup instead if this migration must be undone."
    )
