"""add is_admin to users

Revision ID: cc2bdd0271c2
Revises: a43bc5460e9b
Create Date: 2026-09-03 17:56:12.536844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2bdd0271c2'
down_revision: Union[str, Sequence[str], None] = 'a43bc5460e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.

    NEEDED A MANUAL FIX after autogenerate: the raw autogenerated
    `add_column` had no `server_default` - adding a NOT NULL column
    with no default to a table that already has real rows (`users`
    has live accounts) fails outright in Postgres, since every
    existing row would otherwise have no value to put there.
    `server_default='false'` fills every existing row with `false`
    (nobody is an admin by default) at the DATABASE level, which is
    what actually matters for the ALTER TABLE itself - models.py's own
    Python-side `default=False` only ever applies to rows inserted
    later, through the ORM, and does nothing for rows that already
    exist.
    """
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
